/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.crazynerve.models;
@org.apache.avro.specific.AvroGenerated
public enum Sex implements org.apache.avro.generic.GenericEnumSymbol<Sex> {
  MALE, FEMALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Sex\",\"namespace\":\"com.crazynerve.models\",\"symbols\":[\"MALE\",\"FEMALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
